### DISCUSSION TITLE
Snap package management thread

### DISCUSSION THREAD

**Discussion by soumyaDghosh** [Heroic-Games-Launcher/HeroicGamesLauncher#3127] [Ideas]
@flavioislima Creating this thread to discuss regarding the snap package.

```
name: heroic
base: core22 
version: '2.9.2' 
summary: Single-line elevator pitch for your amazing snap 
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel
confinement: devmode 
compression: lzo

parts:
  heroic:
    plugin: dump
    source: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v$SNAPCRAFT_PROJECT_VERSION/heroic_$SNAPCRAFT_PROJECT_VERSION_$CRAFT_TARGET_ARCH.deb
    
apps:
  heroic:
    command: opt/Heroic/heroic
    desktop: usr/share/applications/heroic.desktop
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    extensions:
      - gnome
```

This is the current starter yaml. But, obviously this would change a lot. Now, the first thing that needs to be changed upstream is

```
(11:24:10) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/soumyaxubuntu/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(11:24:10) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/soumyaxubuntu/.config/heroic/gog_store/auth.json --version
(11:24:10) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/soumyaxubuntu/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
```

The `XDG_CONFIG_HOME` should be changed to `/home/soumyaxubuntu/snap/heroic/x1/.config` which is the real one for snaps. I guess the app is forcing `XDG_CONFIG_HOME` while running.

**Comment by flavioislima** [comment]
Thanks again for looking into that @soumyaDghosh.

I believe we are doing this to avoid conflicts when someone is using legendary standalone along with Heroic. 
We can add an if check to use another path if we are able to detect we are under a snap config.
How can we do that? checking if some snap env variable is setup? that should work I believe, I will try.

Line of code if you want to take a look:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/1020e7e2d6fb5379613f8d96b3d61036c7cb0d00/src/backend/storeManagers/legendary/library.ts#L669

I will try locally to see if it fixes the Epic login issue.

**Reply by soumyaDghosh** [reply]
We can check for the existense of an environment variable `SNAP`. Okay, now I will add up extra things. One by one.

EDIT: No change is necessary. Everything is fine.

**Comment by flavioislima** [comment]
That did the trick, one problem solved! 🎉 

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/26871415/2c496e8a-96b3-464e-b185-1df8710724a5)

Now we need to figure it out how to have access to `curl`, gamemode, mangohud, gamescope and the Steam and Lutris folders.

**Reply by soumyaDghosh** [reply]
BTW, if you're using wayland, this is running on wayland :-)
I didn't disable it.

**Reply by flavioislima** [reply]
Yes this is Wayland :D 
But I generated the snap using electron-builder for now. If we can make it work with it is better because then I don't need to change the CI workflows that are already working for Snaps so they get updated automatically on every release.

This is the current yml generated by it:
```
base: core20
grade: stable
confinement: strict
plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  dot-local-share:
    interface: personal-files
    write:
      - $HOME/.local/share/Steam
      - $HOME/.local/share/lutris
name: heroic
version: 2.9.2
title: Heroic
summary: Heroic
description: Heroic is an Open Source Games Launcher. Right now it supports launching games from the Epic Games Store using Legendary and GOG Games using our custom implementation with gogdl.
architectures:
  - amd64
apps:
  heroic:
    command: command.sh
    plugs:
      - desktop
      - desktop-legacy
      - home
      - x11
      - wayland
      - unity7
      - browser-support
      - network
      - gsettings
      - audio-playback
      - pulseaudio
      - opengl
      - dot-local-share
    environment:
      DISABLE_WAYLAND: ''
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
      LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu
```
