### ISSUE TITLE
"Add to Lutris" button

### ISSUE THREAD

**Issue by tobil4sk** [Heroic-Games-Launcher/HeroicGamesLauncher#2619]
### Problem description

Currently, if you want to add your Heroic games to Lutris, you need to manually add them and add the Heroic launch command, for example, `heroic --no-gui "heroic://launch/530f09c9ac834a7bbc98056c69b44471"`. This is quite tedious to do for every game.

### Feature description

It would be nice to have an "Add to Lutris" button, that works like the "Add to Steam" button and provides an easy way to add the game to the Lutris library, without having to manually input all the information.

### Alternatives

Alternatively, Lutris could allow Heroic to be used as a source, but from https://github.com/lutris/lutris/issues/3778 and from reading old Discord message logs it looks like they don't seem interested in providing this themselves.

**Comment by yeetsquad747** [comment]
i hope this goes through.

**Comment by PermaFreez** [comment]
I came here from the lutris thread where you mentioned this, I've been going there every month or two, in the past hoping there was progress. We need this.

**Comment by Nocccer** [comment]
Could be easy if there is an easy way to add games to lutris? Can you tell me how you can add games via cli or via editing a file from lutris? Is there maybe an npm package already?

**Comment by tobil4sk** [comment]
> Can you tell me how you can add games via cli or via editing a file from lutris

It's possible to add games to lutris using the lutris cli and yml files. For example, here is a simple yml file for installing a Heroic game:

```yaml
name: Test Game
game_slug: test-game
version: Heroic
slug: test-game-heroic
runner: linux

year: 2000 # optional, just so lutris displays the correct release year

script:
  game:
    exe: /usr/bin/heroic
    args: --no-gui heroic://launch/{{game-id}}
```

Heroic could generate a file like this and run it using `lutris --install /full/path/to/install.yml`.

Unfortunately, this lutris command launches the lutris installation GUI, I'm not sure if there is a pure cli version.

Also, the `game_slug` identifier must be the same as in the lutris database, otherwise the game's images will be empty. This may be an issue.
