### ISSUE TITLE
Allow sideloading from all files in a directory

### ISSUE THREAD

**Issue by drbloop** [Heroic-Games-Launcher/HeroicGamesLauncher#4569]
### Problem description

I would like to be able to sideload games into Heroic by placing JSON or YAML definition files in the sideloads directory.

I am working on automating game installations across gaming computers, using Heroic as the launcher. I have this working okay with some games, but the workflow is clunky because all sideload games are loaded from the single file `$HOME/.config/heroic/sideload_apps/library.json`. With a single file you have to write automation to merge JSON as you add and remove games. This workflow feels complex and error-prone to me, and everyone wanting to automate Heroic game installs like I am currently needs to implement their own solution.

This is how I am currently merging sideloads, in Ansible:

```yml
- name: render heroic sideload config
  become: false
  when: not stat_game_dir.stat.exists  # only do this once, ordering is inconsistent
  block:
  - stat:
      path: "{{common_facts_user_homedir}}/.config/heroic/sideload_apps/library.json"
    register: stat_sideload_json

  - name: generate initial config
    when: not stat_sideload_json.stat.exists
    block:
    - name: run heroic once to generate initial config
      command:
        cmd: 'heroic --version'
        creates: "{{common_facts_user_homedir}}/.config/heroic/sideload_apps"

    - copy:
        dest: "{{common_facts_user_homedir}}/.config/heroic/sideload_apps/library.json"
        content: '{}'

  - slurp:
      src: "{{common_facts_user_homedir}}/.config/heroic/sideload_apps/library.json"
    register: slurp_sideload

  - set_fact:
      sideload_existing_content: "{{slurp_sideload.content|b64decode|from_json}}"
      sideload_new_content: "{{lookup('template', 'templates/heroic_game_linux.yml.j2')|from_yaml}}"

  # - debug: var=sideload_existing_content
  # - debug:
  #     var: "{{sideload_new_content}}"

  - set_fact:
      sideload_merged_content: "{{sideload_existing_content | combine(sideload_new_content, list_merge='append_rp')|to_nice_json(indent=2)}}"
  # - debug:
  #     var: sideload_merged_content

  - name: write merged sideloads file
    copy:
      dest: "{{games_heroic_sideload_file}}"
      content: "{{sideload_merged_content}}"
```

### Feature description

It would be nice if Heroic could import any json/yaml files stored in directory `$HOME/.config/heroic/sideload_apps/`. Then for each game to install my automation could render a new template into that sideloads directory instead of trying to merge on my end. 

The code that renders the `library.json` file is here, https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/src/backend/storeManagers/sideload/electronStores.ts#L5. I am too new to TypeScript to understand if a fileglob could be passed to the [electron_store](https://github.com/sindresorhus/electron-store) `libraryStore` constructor in source here.

I think this change could help other users too, with automation and also debugging sideload problems.

### Alternatives

This could be opt in with a config variable, `HEROIC_SIDELOADS_EXTRA_DIR` or something.
